### ISSUE TITLE
Default RPC and private key to development environment values

### ISSUE THREAD

**Issue by izqui** [aragon/aragon-dev-cli#18]
When running any commands with no rpc node is provided as a flag and there is no HTTP server listening at port 8545, I think it would be a good idea to start a testrpc node in the background with a huge amount of ETH for a dummy private key `0x1111...`. 

Using this with #17 would allow for easy development with almost no setup.

**Comment by onbjerg** [comment]
I agree. I moved this to the backlog. I think we can include this in 1.0.0.
