### ISSUE TITLE
Reverts after first version is published

### ISSUE THREAD

**Issue by luisivan** [aragon/aragon-dev-cli#72]
Steps to reproduce:
```
aragon init test.aragonpm.eth bare
cd test
aragon run
aragon version minor
aragon run
```

**Comment by izqui** [comment]
It reverts because you are upgrading a contract in a minor version, APM only allows doing so in major versions. Just tested it with `aragon version major` and it works as expected.

**Comment by luisivan** [comment]
Throws for me as well when doing major
