### ISSUE TITLE
Integration with Truffle

### ISSUE THREAD

**Issue by onbjerg** [aragon/aragon-dev-cli#9]
Right now the workflow is one of:

- `truffle build`
- `truffle deploy`
- `aragon-dev-cli publish`
- Sign and broadcast transaction

It would be cool if we could do something like

- `truffle deploy`

which would build the application, deploy the contracts, generate the artifacts and publish the application to IPFS.

**Comment by onbjerg** [comment]
Going from discussions with @izqui, we might not want to integrate with truffle, but instead just depend directly on solc. The flow would be something like

```
aragon build
aragon publish
```

or alternatively `publish` should also do `build` if `build` was not already run. For tests, we could have a test command. This would lower the barrier to entry, since no one would need to install truffle as well to work on Aragon apps.

Because of this, we should probably close the issue. Agree @izqui?

**Comment by izqui** [comment]
I started working on the build tool already: https://github.com/aragon/pig

`aragon build` could do `pig` in the background and that's it :)

**Comment by onbjerg** [comment]
ok

**Comment by luisivan** [comment]
In the latest beta, `aragon contracts <args>` passes through the args to Truffle. It also compiles using Truffle in `aragon run`, so I'll close this for now (until maybe in the future we use pig, then we can open a new issue for that)
